language: cpp
sudo: false

matrix:
  include:
    - os: linux
      compiler: gcc
    - os: linux
      compiler: clang
    - os: osx
      compiler: clang
    - os: windows
      compiler: gcc
      install:
        - wget -O googletest.zip https://github.com/google/googletest/archive/release-1.8.1.zip
        - 7z x googletest.zip
        - cd googletest-release-1.8.1/googletest
        - g++ -std=c++11 -isystem include -I . -pthread -c src/gtest-all.cc
        - mv gtest-all.o ../../cpp/tests/libgtest.lib
        - cd ../..
      script:
        - cd cpp/tests
        - mingw32-make
        - ./cpp-test-all.exe
        - cd ../..

install:
  - GTESTVERSION=1.8.1
  - wget -O googletest.tar.gz https://github.com/google/googletest/archive/release-$GTESTVERSION.tar.gz
  - tar xf googletest.tar.gz
  - cd googletest-release-$GTESTVERSION
  - cd googletest
  - $CXX -std=c++11 -isystem include -I . -pthread -c src/gtest-all.cc
  - mv gtest-all.o ../../cpp/tests/libgtest.a
  - cd ../..

script:
  - make -C cpp/tests
  - ./cpp/tests/cpp-test-all

notifications:
  email: false
