language: cpp
sudo: false

matrix:
  include:
    - os: linux
      compiler: gcc
    - os: linux
      compiler: clang
    - os: osx
      compiler: gcc
    - os: osx
      compiler: clang
    - os: windows
      compiler: gcc

install:
  - GTESTVERSION=1.8.1
  - wget -O googletest.tar.gz https://github.com/google/googletest/archive/release-$GTESTVERSION.tar.gz
  - tar xf googletest.tar.gz
  - cd googletest-release-$GTESTVERSION
  - cd googletest
  - $CXX -std=c++11 -isystem include -I . -pthread -c src/gtest-all.cc
  - if [ "$TRAVIS_OS_NAME" == "windows" ]; then GTEST_NAME=libgtest.lib; else GTEST_NAME=libgtest.a; fi
  - mv gtest-all.o ../../cpp/tests/$GTEST_NAME
  - cd ../..

script:
  - if [ "$TRAVIS_OS_NAME" == "windows" ]; then MAKE_PROGRAM=mingw32-make; else MAKE_PROGRAM=make; fi
  - $MAKE_PROGRAM -C cpp/tests
  - ./cpp/tests/cpp-test-all

notifications:
  email: false
